
const DATA={stats:{submissions:67,selected:2,notSelected:28,waiting:37},today:[["Jordan International Film Festival","موعد نتیجه رسیده؛ هنوز سند رسمی قطعی برای نتیجه نهایی ثبت نشده است.","نیازمند بررسی"],["رجیستری ضدتکرار","۶۷ ارسال قبلی در حافظه پرونده ثبت شده و قبل از هر فرصت تازه کنترل می‌شود.","فعال"],["قفل اطلاعات فیلم","سال ۲۰۲۵، مدت ۱۶:۵۰ و مشخصات مرجع از رکورد ثابت خوانده می‌شوند.","فعال"]],festivals:[["Jordan International Film Festival","JFF15879","نتیجه اعلام نشده","۱۴۰۵/۰۶/۰۶","نیازمند بررسی"],["Jangsu Mountain Village Film Festival","JMVFF6138","نتیجه اعلام نشده","۱۴۰۵/۰۶/۰۸","در انتظار"],["Gandhara Independent Film Festival","GIFF2457","نتیجه اعلام نشده","۱۴۰۵/۰۶/۰۹","در انتظار"],["Kuçova International Independent Film Festival","3754","نتیجه اعلام نشده","۱۴۰۵/۰۶/۱۵","در انتظار"],["Uppsala Short Film Festival","FFW264812","نتیجه اعلام نشده","۱۴۰۵/۰۶/۳۰","در انتظار"],["Tampere Film Festival","TFF26-3212","انتخاب‌نشده","—","مسدود"],["Vienna Shorts","—","عدم اقدام استراتژیک","—","مسدود"]],decisions:[["Tampere Film Festival","مسدود","قبلاً ارسال شده و نتیجه انتخاب‌نشده ثبت شده","فقط با تغییر مستند شرایط"],["Vienna Shorts","مسدود","بخش مناسب برای فیلم وجود نداشت","فقط با تغییر رسمی قوانین"],["Square Eyes","بسته","سال تولید ۲۰۲۵ برای سیاست فعلی آنها قدیمی تلقی شد","فقط با تغییر سیاست یا تماس دوباره سازمان"],["shnit","نیازمند بررسی","وضعیت نهایی تحویل قطعی نیست","پس از اثبات وضعیت نهایی"]]};

const modal=document.getElementById("loginModal"),portal=document.getElementById("portal"),portalContent=document.getElementById("portalContent");
document.querySelectorAll("[data-open-login]").forEach(b=>b.onclick=()=>{modal.classList.add("show");modal.setAttribute("aria-hidden","false")});
document.querySelectorAll("[data-close-login]").forEach(b=>b.onclick=()=>{modal.classList.remove("show");modal.setAttribute("aria-hidden","true")});
function openPortal(){modal.classList.remove("show");portal.classList.add("show");portal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";renderView("overview")}
document.getElementById("loginSubmit").onclick=openPortal;document.getElementById("quickDemo").onclick=openPortal;
document.getElementById("portalExit").onclick=()=>{portal.classList.remove("show");portal.setAttribute("aria-hidden","true");document.body.style.overflow=""};

const slides=[...document.querySelectorAll(".benefit-slide")],dots=document.getElementById("sliderDots");let si=0;
slides.forEach((_,i)=>{const b=document.createElement("button");if(i===0)b.className="active";b.onclick=()=>showSlide(i);dots.appendChild(b)});
function showSlide(i){si=i;slides.forEach((s,x)=>s.classList.toggle("active",x===i));[...dots.children].forEach((d,x)=>d.classList.toggle("active",x===i))}
setInterval(()=>showSlide((si+1)%slides.length),4700);
const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.1});document.querySelectorAll(".reveal").forEach(e=>obs.observe(e));

function status(v){let c=/مسدود|بسته|انتخاب‌نشده/.test(v)?"block":/بررسی|انتظار|اعلام نشده/.test(v)?"warn":"ok";return `<span class="status ${c}">${v}</span>`}
function table(rows,heads){return `<div class="table-wrap"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>`<td>${i===r.length-1?status(v):v}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
function renderView(v){
document.querySelectorAll(".portal-nav nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===v));
if(v==="overview")portalContent.innerHTML=`<div class="portal-body"><section class="portal-hero"><div class="portal-hero-copy"><small>پرونده فعال</small><h2>ناگهان برمی‌خیزد</h2><p>۲۰۲۵ · ایران · ۱۶:۵۰ · فارسی با زیرنویس انگلیسی · رئالیسم جادویی / درام</p>${status("فعال")}</div><img src="./assets/sudden-rise-hero.jpg"></section><div class="metrics"><div class="metric"><small>ارسال ثبت‌شده</small><b>67</b><small>رجیستری</small></div><div class="metric"><small>انتخاب‌شده</small><b>2</b><small>ثبت قطعی</small></div><div class="metric"><small>انتخاب‌نشده</small><b>28</b><small>بسته</small></div><div class="metric"><small>در انتظار</small><b>37</b><small>پایش</small></div></div><div class="dashboard-grid"><div class="panel"><h3>امروز چه تغییر کرد؟</h3>${DATA.today.map(x=>`<div class="event"><b>${x[0]}</b><p>${x[1]}</p>${status(x[2])}</div>`).join("")}</div><div class="panel"><h3>ورود سریع</h3><div class="quick-actions">${[["film","پرونده فیلم"],["festivals","جشنواره‌ها"],["calendar","تقویم نتایج"],["decisions","حافظه تصمیم"],["guard","نگهبان حیثیت"]].map(x=>`<button data-goto="${x[0]}"><b>${x[1]}</b><small>مشاهده بخش</small></button>`).join("")}</div></div></div></div>`;
if(v==="film")portalContent.innerHTML=`<div class="portal-body"><section class="portal-hero"><div class="portal-hero-copy"><small>SUDDEN RISE</small><h2>ناگهان برمی‌خیزد</h2><p>نویسنده، تهیه‌کننده و کارگردان: محمد سجاد مطهری‌زاده</p><p>ایران · ۲۰۲۵ · ۱۶:۵۰ · فارسی · زیرنویس انگلیسی · ۴:۳ · فیلم کوتاه داستانی · رئالیسم جادویی / درام</p></div><img src="./assets/sudden-rise-portrait.jpg"></section><div class="panel" style="margin-top:14px"><h3>خلاصه داستان</h3><p style="color:#888;line-height:2">در روستایی دورافتاده، سنگی مقدس برای نسل‌ها زندگی و اقتصاد مردم را شکل داده است. وقتی مردی درون سنگ گرفتار می‌شود، ماجرا به جدالی اخلاقی میان ایمان، منفعت، بقای جمعی و ارزش جان انسان تبدیل می‌شود.</p></div></div>`;
if(v==="festivals")portalContent.innerHTML=`<div class="portal-body"><h3>رجیستری جشنواره‌ها</h3>${table(DATA.festivals,["جشنواره","کد پیگیری","وضعیت داوری","موعد نتیجه","وضعیت ایجنت"])}</div>`;
if(v==="calendar")portalContent.innerHTML=`<div class="portal-body"><h3>تقویم شمسی نتایج</h3>${table(DATA.festivals.filter(x=>x[2].includes("اعلام نشده")).map(x=>[x[0],x[3],x[4]]),["جشنواره","موعد نتیجه","وضعیت"])}</div>`;
if(v==="decisions")portalContent.innerHTML=`<div class="portal-body"><h3>حافظه تصمیم</h3>${table(DATA.decisions,["موجودیت","تصمیم","دلیل","شرط بازگشایی"])}</div>`;
if(v==="guard")portalContent.innerHTML=`<div class="portal-body"><div class="dashboard-grid"><div class="panel"><h3>قانون ضدتکرار</h3><div class="event"><b>قبل از هر ثبت‌نام</b><p>فیلم، جشنواره، دوره، بخش و سابقه پخش‌کننده بررسی می‌شود.</p>${status("مسدود")}</div><div class="event"><b>قبل از هر ایمیل</b><p>نام سازمان، دامنه، گیرنده و زنجیره قبلی بررسی می‌شود.</p>${status("مسدود")}</div></div><div class="panel"><h3>اصل توقف در ابهام</h3><p style="color:#888;line-height:2">اگر داده کلیدی نامشخص، ناقص یا متناقض باشد، ایجنت حق اقدام بیرونی ندارد.</p>${status("نیازمند بررسی")}</div></div></div>`;
portalContent.querySelectorAll("[data-goto]").forEach(b=>b.onclick=()=>renderView(b.dataset.goto));
}
document.querySelectorAll(".portal-nav nav button").forEach(b=>b.onclick=()=>renderView(b.dataset.view));
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
